//@host = http://rasp3
@host = http://localhost:5000
@api = {{host}}/api

GET {{host}}

###
GET {{api}}/led

###
GET {{api}}/reset


###

GET {{api}}/led/2

### Update value
GET {{api}}/led/0/_flick
###
GET {{api}}/led/1/_flick
###
GET {{api}}/led/2/_flick
###
GET {{api}}/led/3/_flick
###
GET {{api}}/led/4/_flick
###
GET {{api}}/led/5/_flick
###
GET {{api}}/led/6/_flick
###
GET {{api}}/led/12/_flick

### Update display name
PUT {{api}}/led/2
Content-Type: application/json

{
  "foo": "Bla - totally ignored property",
  "display": "Yo dude",
  "other": "Bla - totally ignored property"
}

### TODO:
### bank and port
GET {{api}}/leds/bank/4/led/0