name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.*
    - name: Build 
      run: dotnet build --configuration Release LightControl.sln
    - name: Run unit tests
      run: dotnet test
    - name: Publish
      run: dotnet publish light-control-api/light-control-api/src/LightControl.Api/LightControl.Api.csproj --configuration Release --runtime linux-arm --self-contained true -o website
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: website
        path: light-control-api/website/**
        if-no-files-found: Error
